package com.emsi.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "miniprojet")
public class Contact implements java.io.Serializable {

	private Integer idContact;
	private User user;
	private String nomContact;
	private String prenomContact;
	private String telContact;

	public Contact() {
	}

	public Contact(User user) {
		this.user = user;
	}

	public Contact(User user, String nomContact, String prenomContact, String telContact) {
		this.user = user;
		this.nomContact = nomContact;
		this.prenomContact = prenomContact;
		this.telContact = telContact;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idContact", unique = true, nullable = false)
	public Integer getIdContact() {
		return this.idContact;
	}

	public void setIdContact(Integer idContact) {
		this.idContact = idContact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "nomContact", length = 254)
	public String getNomContact() {
		return this.nomContact;
	}

	public void setNomContact(String nomContact) {
		this.nomContact = nomContact;
	}

	@Column(name = "prenomContact", length = 254)
	public String getPrenomContact() {
		return this.prenomContact;
	}

	public void setPrenomContact(String prenomContact) {
		this.prenomContact = prenomContact;
	}

	@Column(name = "telContact", length = 254)
	public String getTelContact() {
		return this.telContact;
	}

	public void setTelContact(String telContact) {
		this.telContact = telContact;
	}
	

}
