package com.emsi.model;

import java.util.ArrayList;

// default package
// Generated Dec 26, 2018 8:19:27 AM by Hibernate Tools 4.3.5.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "miniprojet")
public class User implements java.io.Serializable {

	private Integer idUser;
	private String nomUser;
	private String login;
	private String mdp;
	private List<Contact> contacts = new ArrayList<Contact>(0);

	public User() {
	}

	public User(String nomUser, String login, String mdp, List<Contact> contacts) {
		this.nomUser = nomUser;
		this.login = login;
		this.mdp = mdp;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void ListIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "nomUser", length = 254)
	public String getNomUser() {
		return this.nomUser;
	}

	public void ListNomUser(String nomUser) {
		this.nomUser = nomUser;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void ListLogin(String login) {
		this.login = login;
	}

	@Column(name = "mdp", length = 254)
	public String getMdp() {
		return this.mdp;
	}

	public void ListMdp(String mdp) {
		this.mdp = mdp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<Contact> getContacts() {
		return this.contacts;
	}

	public void ListContacts(List<Contact> contacts) {
		this.contacts = contacts;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public void setContacts(List<Contact> contacts) {
		this.contacts = contacts;
	}
	
	

}
